name: ci
run-name: CI ${{ github.ref }}
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - README.md
      - LICENSE.txt
      - .gitignore
      - .vscode/**
      - .devcontainer/**

jobs:
  build_python:
    name: Python | build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements-dev.txt
      - run: |
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 120 chars wide.
          flake8 . --count --per-file-ignores='__init__.py:F401' --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - run: python -m pytest --cov=sag_py_logging_logstash --cov-report=xml tests
      - run: coverage-lcov
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
